### PR TITLE
Unity Video

### PR DESCRIPTION
**Pull request by yanniektan**
WebGL decided not to work so I just made a use-case scenario to cover the splash page for now.

All one has to do to test it is to run the app.

### CODE REVIEW

**Review by iStebz — CHANGES_REQUESTED** [review]
I think a file is missing - David.mp4 isn't added in this PR so I'm unable to build the website.

**Comment by yanniektan** [comment]
Try now.

**Review by iStebz — CHANGES_REQUESTED** [review]
Video is off center when I tested: 
image

Also, please remove or disable the splash screen if we are no longer using it. I've added Katherine as a review as well, since this change affects some of the elements she added.

**Comment by katchen1** [comment]
Hey @yanniektan, thanks for embedding the video. I fixed the off-centered issue, and added a start engine button for the splash screen.

If it's okay, I'm going to bring back the content that you removed in `Header.js` (our product's title, description, buttons), and keep it overlayed over the video. This will make it easier to integrate with [my changes](https://github.com/Esteban-Wu/CS-210-Website/pull/6/files#diff-a39c6761048438cf69aafee414dbf1594abf54752ab1f1c9eb5a241ba5d315a9) (which is already up on the [public website](https://esteban-wu.github.io/CS-210-Website/)). I think it would be a better experience for the viewer to see this info up front without having to scroll down, otherwise they would be confused by the video.

Re-requesting a review from @Esteban-Wu.

**Review by iStebz — COMMENTED** [review]
LGTM, tested and start engine button + video works as intended

**Review by iStebz — APPROVED** [review]

**Pull request merged**
